#!/usr/bin/env bash
# tune-client-os.sh
# Apply OS-level kernel parameters for NetApp AFX benchmark clients
#
# Usage: sudo ./tune-client-os.sh [--persistent]
#
# Applies:
#   sunrpc.rdma_slot_table_entries = 200   (RDMA slot table for NFS over RDMA)
#   vm.dirty_background_bytes = 2147483648 (2 GB dirty page background writeback)
#   vm.dirty_bytes            = 5368709120 (5 GB dirty page hard limit)
#   vm.dirty_background_ratio = 0          (disable ratio-based thresholds)
#   vm.dirty_ratio            = 0          (disable ratio-based thresholds)
#   vm.dirty_expire_centisecs = 300        (dirty pages expire after 3 seconds)
#   vm.dirty_writeback_centisecs = 100     (writeback runs every 1 second)
#
# Use --persistent to write values to /etc/sysctl.d/90-netapp-afx-benchmark.conf

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: This script must be run as root (sudo)." >&2
    exit 1
fi

PERSISTENT=false
if [[ "${1:-}" == "--persistent" ]]; then
    PERSISTENT=true
fi

echo "=== NetApp AFX Benchmark OS Tuning ==="

declare -A SYSCTL_PARAMS
SYSCTL_PARAMS[sunrpc.rdma_slot_table_entries]=200
SYSCTL_PARAMS[vm.dirty_background_bytes]=2147483648
SYSCTL_PARAMS[vm.dirty_bytes]=5368709120
SYSCTL_PARAMS[vm.dirty_background_ratio]=0
SYSCTL_PARAMS[vm.dirty_ratio]=0
SYSCTL_PARAMS[vm.dirty_expire_centisecs]=300
SYSCTL_PARAMS[vm.dirty_writeback_centisecs]=100

for PARAM in "${!SYSCTL_PARAMS[@]}"; do
    VALUE="${SYSCTL_PARAMS[$PARAM]}"
    echo "  Setting $PARAM = $VALUE"
    sysctl -w "${PARAM}=${VALUE}" || echo "  WARNING: Could not set $PARAM (may require kernel module)"
done

if $PERSISTENT; then
    CONF_FILE="/etc/sysctl.d/90-netapp-afx-benchmark.conf"
    echo ""
    echo "--- Writing persistent config to $CONF_FILE ---"
    cat > "$CONF_FILE" <<'SYSCTL_EOF'
# NetApp AFX Benchmark Client OS Tuning
# Generated by tune-client-os.sh
# Reference: https://github.com/whyistheinternetbroken/AFXTestPlans/blob/main/setup.adoc

# RDMA slot table for sunrpc (required for NFS over RDMA performance)
sunrpc.rdma_slot_table_entries = 200

# Dirty page writeback tuning for high-throughput NFS writes
# Use byte-based thresholds and disable ratio-based thresholds
vm.dirty_background_bytes = 2147483648
vm.dirty_bytes = 5368709120
vm.dirty_background_ratio = 0
vm.dirty_ratio = 0

# Writeback timing
vm.dirty_expire_centisecs = 300
vm.dirty_writeback_centisecs = 100
SYSCTL_EOF
    echo "  Written. Will be applied automatically at next boot."
    echo "  To apply immediately: sysctl -p $CONF_FILE"
fi

echo ""
echo "=== OS tuning complete ==="
if ! $PERSISTENT; then
    echo "NOTE: Settings are applied dynamically and will not persist across reboots."
    echo "      Re-run with --persistent to write to /etc/sysctl.d/"
fi
